STOP_LOSS = 20
TARGET = 40
MODE = "PAPER"   # PAPER / LIVE

BROKER = "DHAN"  # DHAN / ZERODHA / ANGEL / KOTAK

LOT_SIZE = int(input("Lot Size Enter Kare: "))
TELEGRAM_TOKEN ="8778860843:AAHd06Hpdx5K5wy9ay0mvH-n1umvBesl8W8"
CHAT_ID ="2019899357"


BROKER = "DHAN"

DHAN_CLIENT_ID = ""
DHAN_ACCESS_TOKEN = ""

ZERODHA_API_KEY = ""
ZERODHA_ACCESS_TOKEN = ""

ANGEL_API_KEY = ""
ANGEL_CLIENT_CODE = ""

KOTAK_CONSUMER_KEY = ""
